# Use official PHP container with webserver on board
FROM php:7.1-apache

RUN apt-get update && apt-get install -y locales wget git zip unzip curl

RUN echo "Europe/Paris" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="fr_FR.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=fr_FR.UTF-8

# Needed to build intl ext
RUN apt-get install -y zlib1g-dev libicu-dev libfontconfig1-dev libjpeg62-turbo-dev libpng12-dev libfreetype6-dev g++ curl libcurl3 \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install mysqli intl pdo_mysql gd

# xDebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini

# Copy required configuration files
COPY app.conf /etc/apache2/sites-available/000-default.conf
COPY app.ini /usr/local/etc/php/conf.d/

# Apache settings
RUN a2enmod rewrite \
    && a2enmod proxy \
    && a2enmod headers \
    && a2enmod proxy_http \
    && a2enmod ssl

# Get composer
RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer \
    && chmod +x /usr/local/bin/composer

RUN mkdir -p /var/lib/php/sessions && chown -R www-data /var/lib/php && chmod -R 775 /var/lib/php/sessions


# Get node and yarn
## install Node.js LTS
RUN curl -sL 'https://deb.nodesource.com/setup_6.x' | bash /dev/stdin

## install yarn package manager
RUN curl -sS 'https://dl.yarnpkg.com/debian/pubkey.gpg' | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get -y update && apt-get install -y nodejs yarn

# ENV
ENV LC_ALL="fr_FR.UTF-8"
ENV LANG="fr_FR.UTF-8"
ENV LANGUAGE="fr_FR.UTF-8"

RUN usermod -u 1000 www-data

WORKDIR /var/www/html